
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
      - VITE_REACT_API_URL=http://127.0.0.1:8080/api
    container_name: frontend_app
    ports:
      - "8081:80"
    volumes:
      - ./src:/app/src
    networks:
      - frontend-network

  nginx:
    image: nginx:alpine
    container_name: frontend_nginx
    ports:
      - "8082:80"
    volumes:
      - ./dist:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./logs:/var/log/nginx-custom
    environment:
      - VITE_REACT_API_URL=http://127.0.0.1:8080/api
    depends_on:
    - frontend
    networks:
    - frontend-network

networks:
  frontend-network:
    driver: bridge