FROM node:24-alpine as build
WORKDIR /app
COPY package* .
RUN npm install
COPY . .
ARG VITE_REACT_API_URL
ENV VITE_REACT_API_URL=${VITE_REACT_API_URL}
RUN npm run build 


FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf