FROM node:24 as build
WORKDIR /app
COPY package* .
RUN npm install
COPY . .
# RUN npm run build
ARG REACT_APP_API_URL
ENV REACT_APP_API_URL=${REACT_APP_API_URL}

# FROM nginx:alpine
# COPY --from=build /app/build /usr/share/nginx/html
# COPY nginx.conf /etc/nginx/conf.d/default.conf


EXPOSE 3000
CMD [ "npm","run","dev" ]